apiVersion: v1
kind: Service
metadata:
  name: mdai-s3-logs-reader-service
  namespace: mdai
  labels:
    app: mdai-s3-logs-reader
spec:
  selector:
    app: mdai-s3-logs-reader
  ports:
    - port: 4400
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
